trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  uiSource: 'src'
  uiBuild: '$(uiSource)/dist'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'

# Cache npm modules based on the *root* package-lock.json
- task: Cache@2
  displayName: 'Cache npm'
  inputs:
    key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
      npm
    path: '$(Pipeline.Workspace)/npm-cache'

- script: |
    npm config set cache $(Pipeline.Workspace)/npm-cache --global
    npm ci
    npm run build --prefix $(uiSource)
  displayName: 'Install dependencies & build Vite'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build as artifact'
  inputs:
    PathtoPublish: '$(uiBuild)'
    ArtifactName: 'static'
    publishLocation: 'Container'
