# Azure Pipelines for ReactJS project

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  uiSource: 'src'
  uiBuild: '$(uiSource)/dist'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# npm cache for speed
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | $(uiSource)/package-lock.json'
    restoreKeys: 'npm | "$(Agent.OS)"'
    path: $(Pipeline.Workspace)/.npm

- script: |
    pushd $(uiSource)
    npm config set cache $(Pipeline.Workspace)/.npm --global
    npm ci
    npm run build
    popd
  displayName: 'npm install and build Vite'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish build as artifact'
  inputs:
    PathtoPublish: '$(uiBuild)'
    ArtifactName: 'static'
    publishLocation: 'Container'